import {ReactNode} from 'react';
import './ui/global.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: Readonly<ReactNode>
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
